### PR TITLE
Regularlise coordinate system

### PR DESCRIPTION
**Pull request by julescmay**
Sorry about the very long explanation of a very simple fix.

In material::Evaluate and ::Sample, the light and eye rays are expressed in a coordinate system which is local to the polygon: to a first approximation the normal to the polygon is aligned along z. Where the polygon carries a u or v, u is aligned along x in the local frame, and v is aligned along y. So far, so good.

But if the poly doesn't provide u and v, then Frame calls Vector::CoordinateSystem to invent one. It uses the polygon normal to create an orthogonal basis. But: there are two bases it could make: one where u is located somewhere on the y=0 plane, and another where v is located on x=0. It chooses based on the direction of the normal.

That means, in turn, that inside ::Evaluate and ::Sample, the light and eye rays can appear in one of two frames, with no way to find out which. So long as the material is isotropic, this doesn't matter. But if the material is anisotropic, it matters very much, because the anisotropy "grain" switches across the face of polygon, creating very objectionable seams.  

I was working with some highly anisotropic materials, but even with the stock materials you can see it. Create a glossy2 or a metal with uroughness=0.7 and vroughness = 0.1, and render a ball. You can see the streaky reflections quite clearly, but you'll also see the seams around it.

cornell-texball ocl error (Incorrect - note seam to the right side of the ball.  Also note very slight seam on the left wall)
cornell-texball ocl (Correct: no seams)

This mod selects the frame where u is horizontal in world space, and v points as vertically as possible (no matter the orientation of the poly). Where the poly faces directly upwards, it adopts a standard frame, were v points along z. Inside ::Evaluate and ::Sample the local frame's x will always have z=0 in world space, and y will almost-always have z != 0.

The change should be invisible to isotropic materials, and should improve anisotropic ones.

### CODE REVIEW

**Comment by Dade916** [comment]
It looks like this patch is mixed with the other one (https://github.com/LuxCoreRender/LuxCore/pull/519) so it is not usable in its current form.

I assume the "Fixes to glossy2 material" commit shouldn't be there.

**Comment by julescmay** [comment]
That's right.  I noticed I'd checked the glossy2 changes into master (and not into the bracnh I thought I was on).  Do you want me to redo this?

**Comment by Dade916** [comment]
Yes, please, we need separate PR for each feature.

**Comment by julescmay** [comment]
Done

**Comment by Dade916** [comment]
Thanks, merged.

**Comment by Dade916** [comment]
Actually, there was an error in the OpenCL code of this patch. It was breaking volume rendering on GPUs ... bugs work in mysterious ways.

**Comment by julescmay** [comment]
Ah - quite right.  Thanks for picking that one up.

**Pull request merged**
