### PR TITLE
Codesigning on azure for OSX

### PR DESCRIPTION
**Pull request by u3dreal**

### CODE REVIEW

**Comment by acasta69** [comment]
I have just a doubt about this line:
[https://github.com/u3dreal/LuxCore/blob/51d85d55ff6901b174c91829da1ccf5ee5a17133/scripts/azurepipeline/macos/codesign.sh#L7](url)
Is that hash meant to be public info, like a public key or similar?
If not, it might be more secure to put it in a secret variable.

**Comment by acasta69** [comment]
There may be a problem in the packing script:
[https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1859&view=logs&j=9451d506-1df1-5410-a0d5-8f998197556f&t=5014ac1b-1505-5222-b5e3-55a81d2b48ec&l=19](url)

**Comment by u3dreal** [comment]
Hell Alessandro ,

the idea of a secret variable would be good …. although you need the hash, the certificate and the password

great you are trying … i’ll have a look at the pack script now

**Comment by u3dreal** [comment]
There was just some line missing .. deleted by accident ... which messed up the folders...

**Comment by u3dreal** [comment]
Hmm .... 
References secure file. PRs from repository forks are not allowed to access secrets in the pipeline. For more information see https://go.microsoft.com/fwlink/?linkid=862029

**Comment by acasta69** [comment]
> and the cert install is a "post" task ??
Let's see how it works after merging... Looking at [the docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops) it seems the post task could be to delete the certificate.

...ok, it seems there's a missing password:
[https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1867&view=logs&j=9451d506-1df1-5410-a0d5-8f998197556f&t=740218c4-6ce2-4179-80d1-592c591e3a58&l=10](https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1867&view=logs&j=9451d506-1df1-5410-a0d5-8f998197556f&t=740218c4-6ce2-4179-80d1-592c591e3a58&l=10)
But as suggested also in log and docs, it would be best to keep it in a secret variable.
Can you access the [variables library](https://dev.azure.com/LuxCoreRender/LuxCoreRender/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=1&path=BuildPipelinesGroup) to add it? If not, I can do it.

**Comment by acasta69** [comment]
I tried to do that (see [589b985](https://github.com/LuxCoreRender/LuxCore/commit/589b985d0328ce71d0ab8929712785e4c81735ee) ), but of course I don't have the right password ;-)
Can you update (or replace) the AppleCertPwd with the correct value?

**Comment by acasta69** [comment]
As you anticipated, maybe something more went wrong:
[https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1869&view=logs&j=9451d506-1df1-5410-a0d5-8f998197556f&t=5014ac1b-1505-5222-b5e3-55a81d2b48ec&l=20](https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1869&view=logs&j=9451d506-1df1-5410-a0d5-8f998197556f&t=5014ac1b-1505-5222-b5e3-55a81d2b48ec&l=20)

**Comment by acasta69** [comment]
... Or maybe it is a normal message?

**Pull request merged**
