### PR TITLE
futher fixes for azure test.sh and local compile script and install.sh

### PR DESCRIPTION
**Pull request by u3dreal**

### CODE REVIEW

**Comment by Dade916** [comment]
You can already check the result here: https://dev.azure.com/LuxCoreRender/LuxCoreRender/_build/results?buildId=1143&view=logs&j=9451d506-1df1-5410-a0d5-8f998197556f&t=78b56764-fca6-5ac0-77d5-9cc50b8c2b09&l=48

It is failing at test stage with:

```
ImportError: dlopen(/Users/runner/runners/2.160.1/work/1/s/pyunittests/pyluxcore.so, 2): Library not loaded: /Users/drquader/Documents/GitHub/MacOSCompileDeps/macos/lib/libtiff.5.dylib
  Referenced from: /Users/runner/runners/2.160.1/work/1/s/pyunittests/pyluxcore.so
  Reason: image not found
```

**Comment by u3dreal** [comment]
Hmm could be a problem with the pyluxcore.so not beeing patched .... it does not work local either.

**Comment by u3dreal** [comment]
It should now produce a .dmg file with all files patched correctly

**Comment by u3dreal** [comment]
testing is disabled for the moment have to look at this later.

**Pull request merged**
