### PR TITLE
Blender hair export

### PR DESCRIPTION
**Pull request by Theverat**
This pull request adds a new Blender-specific hair export method.
Benefits are faster export time and much lower memory usage during export. Also a few new features.

Can you please check the following things:
* For the lower memory usage, I need numpy arrays (Python lists use unnecessary doubles instead of floats). So I had to add `boost_numpy` to the linked libraries in [CMakeLists.txt](https://github.com/LuxCoreRender/LuxCore/compare/blender_hair_export?expand=1#diff-5c1a9f1340db7d23419bd8e5545f2b3e).<br> I [changed the Linux build script](https://github.com/LuxCoreRender/LinuxCompile/commit/2d200db4982ea36f6d4decb0991a7d58da007eb0) to make this work - are similar changes required for Windows (and MacOS?). 
* Also, I could not get the travis build script to work yet, it can't find the boost_numpy library.
* I had to increase `BOOST_PYTHON_MAX_ARITY` from 18 to 22 because the new method needs a lot of parameters. Does this have any detrimental effect?

### CODE REVIEW

**Comment by Dade916** [comment]
I have fixed TravisCI and boost_numpy discovery however  boost_numpy is not part of Windows pre-compiled binaries. @acasta69 please, can you update the WindowCompileDeps repository to include boost_numpy ? It is part of standard boost components ?

**Comment by acasta69** [comment]
Boost_python build generates also boost_numpy if numpy is installed... or at least it should.
This is working with the latest version (1.15.1), but it seems that it is incompatible with the older one shipped with Blender 2.79b. At Blender start I get this:

`found bundled python: C:\Dati\Various\Personal\Tools\Blender\blender-2.79b-windo
ws64\2.79\python
RuntimeError: module compiled against API version 0xc but this version of numpy
is 0xa
ImportError: numpy.core.umath failed to import
Exception in module register(): 'C:\\Users\\italcas1\\AppData\\Roaming\\Blender
Foundation\\Blender\\2.79\\scripts\\addons\\BlendLuxCore\\__init__.py'
ImportError: numpy.core.umath failed to import
`

Does anything similar happen with Linux? Which numpy version are you using there?
I am trying to build with older versions having the required 0xA API, but for some reason boost does not detect them and the lib is not built.
I'm a bit stuck at the moment, but keeping on trying...

**Comment by acasta69** [comment]
Ok, this seems to be solved now, I've built boost_numpy against numpy v. 1.11.3, that is the closest to the 1.10.1 used by Blender and using the same API level. I hope this is not a problem...
I will submit pull requests later today.

**Comment by Theverat** [comment]
Great, thank you!

**Pull request merged**
