### PR TITLE
Adaptive sampling fixes and LuxCoreUI integration

### PR DESCRIPTION
**Pull request by Alpistinho**
As discussed I've implemented the NOISE channel and restored the CONVERGENCE to its original implementation.

I have changed the configurations parameters for convergence and halting threshold, but haven't implemented any backwards compatibility. Is that needed?

LuxCoreUI seems to be working fine, but I haven't done much with it

### CODE REVIEW

**Comment by Dade916** [comment]
Some needed fix:

1) you need the serialize the new channel too (i.e. add a couple of "ar & channel_NOISE;")

2) as you see from the failed Azure build, the convergence test doesn't work. The process was killed after 88,000 samples/pixel. The first test is with BIDIRCPU+Metropolis so I don't know if the problem is strictly related to that case or general.

**Comment by Alpistinho** [comment]
There is no adaptive sampling implemented for Metropolis and I haven't touched it's code, so I don't think it's related to this case.

I guess the tests are still using the old parameters for setting up the convergence, so they're incorrect now and will fail. I will finish the implementation and fix the scenes on the scenes directory. 
Will that be enough to fix the tests?

**Comment by Dade916** [comment]
Uh ? Yes, there reason is probably in changing "batch.haltthreshold" in "batch.noisehaltthreshold" at least. What is the reason of breaking the the compatibility ?

**Comment by Alpistinho** [comment]
@Theverat had suggested it on the forums and there was no objection.

I can revert it or implement the backwards compatibility, as you prefer

**Comment by Theverat** [comment]
Backwards compatibility for the three (?) changed property names would be good in my opinion.
(the related forum post: https://forums.luxcorerender.org/viewtopic.php?f=5&t=1017&start=30#p12030)

**Comment by Alpistinho** [comment]
I've created a new FilmNoiseEstimation class and separated the CONVERGENCE and NOISE calculation completely. Each one has its own set of parameters.

I have implemented the backwards compatibility for the halt threshold, but it doesn't enable the adaptive sampling anymore.
Is this enough?

**Pull request merged**
