### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./deps,./samples/luxcoreui/deps -L avarage,ba,currenty,datas,efficency,heterogenous,homogenous,lod,mapp,pixelx,pres,relfected`

### CODE REVIEW

**Comment by Dade916** [comment]
Thanks.

**Comment by luzpaz** [comment]
Is there any way you can start to deprecate `efficency` in favor of `efficiency`?  Encountered this via a downstream ticket https://github.com/FreeCAD/FreeCAD-render/pull/164#issuecomment-1013628050

**Comment by Dade916** [comment]
It is pretty easy to support both: one for compatibility with the past and the new one.

**Comment by luzpaz** [comment]
@Dade916
Do you mind doing that for:
```
avarage->average
efficency->efficiency
relfected->reflected
```
Thanks for the response

**Comment by Dade916** [comment]
Done.

**Comment by luzpaz** [comment]
@Dade916 don't forget to update the docs?  
https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5#Light_emission

**Pull request merged**
