### PR TITLE
Change Spherelight Implementation (Issue #443)

### PR DESCRIPTION
**Pull request by CodeFHD**
continue to do cone sampling for narrow angles, while only approximating pdfw's etc. with that of a point source.

### CODE REVIEW

**Comment by Dade916** [comment]
I don't understand the patch: from what I see, you are using point light cosThetaAtLight, directPdfW, emissionPdfW and sphere light shadow ray.
It produces a result that is both wrong and doesn't fix the reason why the "if (cosThetaMax > 1.f - DEFAULT_EPSILON_STATIC) {...}" was introduced: shadow banding if sphere light is really small.

I assume if you remove the "if (cosThetaMax > 1.f - DEFAULT_EPSILON_STATIC) {...}", you get the same result but, at least, it computes the correct values (when FP32 allow).

The patch is also missing the fix for the GPU code but that is easy to fix.

**Comment by CodeFHD** [comment]
I have actually been wondering since I submitted if really all those variables need the point-light approximation, I have not compiled through the individual values. My guess would be the directPdfW being most responsible, because in the sphere light it depends on 1-costhetamax which will only go in steps at the float limit, whereas the ray length sqaured of the point light can be much smoother. I could test it if you want.

In the test scenes I made (and the one from Debihood in #443 ) I did not see any banding in shadows when I commented out the condition, only in the light on the mate surface (as shown in the image there)

So the basic idea behind this fix is to keep the approximation of a point light in terms of brightness, and also keep doing the shadow ray test with the spherelight. If I read the code correctly, it is sperated into these parts.

One detail, thinking about it now: perhaps I should have calcualted directdPdfW as centerDistanceSquared, not shadowRayDistanceSquared?

True about the GPU code. I have not worked on that before. If you agree to the fix (or some modification of it), perhaps you could tell me if I need to observe anything special for the GPU code, or edit specific files with it, then I could try to do it.

**Comment by CodeFHD** [comment]
To add a little further info:

I just tested a bit more on Debihoods's scene and a similar one I set up. I can find errors in the shadows at some distance depending on the light radius. However, these becomes apparent much further away from the object than if you do the complete switch to a point source.

Of course I know that FP accuracy can't be tricked indefinitely. I would see this rather as an improvement than a fix in the sense that it could be the solution with the least obvious problems.

**Comment by CodeFHD** [comment]
Just accidentally/automatically closed this because I'm cleaning up my fork.
Do you have any new thoughts on this? Since if yes I would need to still do the GPU code, I might jsut as well reopen then.

**Comment by Dade916** [comment]
I have yet to look into this, yes, reopen it.

**Pull request closed without merging**
