### PR TITLE
Triplanar mapping

### PR DESCRIPTION
**Pull request by Alpistinho**
Hi,

I've started this implementation and would ask someone to have a look to see if this appears to be in the right track.

I am following [this](https://medium.com/@bgolus/normal-mapping-for-a-triplanar-shader-10bf39dca05a) and I think I've got the "Basic Swizzle" method implemented

triplanar

RGB_IMAGEPIPELINE_0

RGB_IMAGEPIPELINE_0

Questions:
* Is this manipulation I did with the HitPoint ok?
* Which of the normals should I use for blending? (Geometric/Interpolated/Shading)

Todo:

- [ ] Finish interface implementation

- [ ] Evaluate the other methods for blending

- [ ] Test

### CODE REVIEW

**Comment by Alpistinho** [comment]
I believe it is working ok enough to put on the main repo and let people on the forums play with it and show me all the 200 ways this is not working as intended.

I will wait for the checks to finish and then merge that, ok?

checkerboard
rock

**Comment by lacilaci** [comment]
Hey, want to test but it seems i cannot download this branch from azure? It only let's me download logs.

**Comment by Dade916** [comment]
> Questions:
>
> Is this manipulation I did with the HitPoint ok?

If you change the UV values, you need to update also all related values: dpdu, dpdv, dndu and dndv.  The code to initialize them is here: https://github.com/LuxCoreRender/LuxCore/blob/095a94b1f467894ef39f1590dcf905b771a97dee/src/slg/bsdf/hitpoint.cpp#L68

Just use a single temporary HitPoint and reuse it to evaluate all 3 directions: not only it is faster (avoid to copy the large HitPoint structure but it is also the only way it can work with OpenCL: there is the space for only a single temporary hitPoint there).

@Alpistinho, you have also to use a TextureMapping3D to transform the HitPoint.p, before to initialize the temporary Hitpoint, so the user can scale, translate rotate the trilineari mapping.

> Which of the normals should I use for blending? (Geometric/Interpolated/Shading)

Geometric Normal si the triangle normal, Interpolated normal is the vertex normal interpolated and Shading normal is the Interpolated normal with bump mapping.

You have probably to use the Interpolated normal.

P.S. remove the 3 unused parsed textures src/slg/scene/parsetextures.cpp

**Comment by Theverat** [comment]
This is a very useful feature, nice work.
Did you test how well the blending works with normal/bump maps yet?

**Comment by Theverat** [comment]
> I have not tried but I suggested to use the Interpolated normal (i.e. without bump applied) exactly to avoid problems if bump/normal mapping is enabled.

I meant blending three normalmaps and use the result for normal mapping.

**Comment by Alpistinho** [comment]
Thanks for the review

I will check the hitpoint issues.

About the mapping, I have been using the mapping on textures that are fed to the Triplanar texture to change it. Do you think that using a 3D mapping is more correct or more intuitive?

**Comment by acasta69** [comment]
> 
> 
> > Hey, want to test but it seems i cannot download this branch from azure? It only let's me download logs.
> 
> @acasta69 may have removed the possibility to store not official builds. You can can ask him to re-enable this feature.

It's because this comes from a pull request. For PRs, the build is done to check for errors, but no build artifacts are uploaded.
Personally I think this behaviour is desirable, otherwise anyone could submit a PR and have binaries published in our repo, but if you want I can change it.

**Comment by lacilaci** [comment]
Oh ok, I understand. Will wait until it's in official daily builds for testing :)

**Comment by Dade916** [comment]
> About the mapping, I have been using the mapping on textures that are fed to the Triplanar texture to change it. Do you think that using a 3D mapping is more correct or more intuitive?

It is a bit cumbersome to have to edit the mapping of 3 input textures; 99.99% of the times, just to input the same values on all 3 of them.

Adding a mapping option directly to the triplanar node will be handy, it is also faster (from the code execution point of view: a single mapping is executed). and it is easy to implement, it is like a single additional line of code (parsing aside).
The option to use the mapping of the 3 input textures will be also still available.

**Comment by Alpistinho** [comment]
@Dade916, about the updating the partial derivatives for point and normal (dpdu, dpdv, dndu, dndv), my understanding is that the textures are being projected into a plane, so these assume fixed values, regardless of the underlying geometry, right?

Something like this (still missing the 3D mapping):
```c++

    hitPointTemp.uv.u = hitPoint.p.y;
    hitPointTemp.uv.v = hitPoint.p.z;

    hitPointTemp.dpdu.x = 0;
    hitPointTemp.dpdu.y = 1;
    hitPointTemp.dpdu.z = 0;

    hitPointTemp.dpdv.x = 0;
    hitPointTemp.dpdv.y = 0;
    hitPointTemp.dpdv.z = 1;

    hitPointTemp.dndu.x = 0;
    hitPointTemp.dndu.y = 0;
    hitPointTemp.dndu.z = 0;
    
    hitPointTemp.dndv.x = 0;
    hitPointTemp.dndv.y = 0;
    hitPointTemp.dndv.z = 0;
    
    Spectrum spectrum = texX->GetSpectrumValue(hitPointTemp)*weights[0];
```

**Comment by Dade916** [comment]
Nope, it the "<delta P or N> / <delta U or V>", how P/N changes at U/V change.

Delta U/V may be constant in your case but P is a point on the object surface, it is not constant. N will be also not constant for any, not planar, object.

Just add a call to GetDifferentials() and print the results, you will see they are not the values you are suggesting.

**Comment by Alpistinho** [comment]
I think I understand what these partial deriavatives values mean. 

However, I thought that since we're projecting the textures from a plane, using its UV values, and not directly into the mesh, the partial derivatives would be calculated using the plane geometry.

If that assumption is incorrect, as it appears to be, then I understand how the partial derivatives will assume values depending on the underlying geometry.

What is the best way for me to compare the results ? Bump Mapping?

**Comment by Dade916** [comment]
The generic code (currently used by your Triplanar texture) is here: https://github.com/LuxCoreRender/LuxCore/blob/3def40b17cd9fa03f78bb7684215f23f3c74acf3/src/slg/textures/texture.cpp#L48

As you can see, it works by sampling the texture on P than again moving slightly along the U axis and than again along the V axis. The differences are used to do bump mapping.

It is a generic implementation that work fine with the vast majority of textures. You can have a custom implementation for various reasons, for instance, image map texture has one that is both faster and avoid artifacs: https://github.com/LuxCoreRender/LuxCore/blob/3def40b17cd9fa03f78bb7684215f23f3c74acf3/src/slg/textures/imagemaptex.cpp#L41

I assume your texture will work fine but it is worth checking. Just do a couple of renderings and check if you get the expected results and no artifacts.
At the end of the day is just a qualitatively evaluation: if it looks fine, it works fine.

**Comment by Dade916** [comment]
@Alpistinho  ?

**Comment by Alpistinho** [comment]
Sorry, a bunch of work stuff got into the middle this past two weeks.

I hope to be able to work on that again this week, although I was having a bit of trouble to understand everything I had to do.

Do you have any timing intention about this issue ?

**Comment by Dade916** [comment]
Aside from writing the OpenCL, I assume it is pretty much done (?).

**Comment by Alpistinho** [comment]
I am coming back to this.

Just rebased the branch and found out that I need to adapt for the new multiple UV feature.
I will let you know about that

**Comment by Theverat** [comment]
Awesome, looking forward to it!

**Comment by Alpistinho** [comment]
I'm facing terrible issues (as usual) to import my build into Blender.

I haven't tested the new code yet, but I hope it is kinda working. Will try to do that soon

**Comment by Alpistinho** [comment]
I think I've got it working as intended again.

Would it be possible for someone else to give it a spin?
I don't really know what to expect outside the trivial cases

**Comment by Theverat** [comment]
I'll check it out next year when I'm back on my PC.

**Comment by lacilaci** [comment]
This is not exposed in blender I assume. Gotta wait for Simon to implement this?

**Comment by Alpistinho** [comment]
@lacilaci ,

There is a matching PR on BlendLuxCore repo, if you want to try that:
https://github.com/LuxCoreRender/BlendLuxCore/pull/320

**Pull request merged**
