### PR TITLE
Add helper function for multi uvmap and multi vertex color support 

### PR DESCRIPTION
**Pull request by neo2068**

### CODE REVIEW

**Comment by Theverat** [comment]
This looks like a lot of code duplication to me, what is the reason for this?
Is it not possible to only replace the single UV pointer in the original function with a list of pointers? (and likewise for vertex colors)

I'm probably missing some detail here.

**Comment by neo2068** [comment]
> This looks like a lot of code duplication to me, what is the reason for this?
> Is it not possible to only replace the single UV pointer in the original function with a list of pointers? (and likewise for vertex colors)
Yes, we could do that. I just copied the scheme of dedicated functions like Dade did for the DefineMesh and DefineMeshExt.

**Comment by Theverat** [comment]
> Is the use of nd::array for type conversion ok?

I think so. You could also use boost::python::list as is done [here](https://github.com/LuxCoreRender/LuxCore/blob/25d466db3ab02784e4ba5a21948232b4db898f81/src/luxcore/pyluxcore.cpp#L840), but it might be more complicated.

**Comment by neo2068** [comment]
Ok. I will replace the old function. I tested the multiuv branch on linux now and it crashes. I will try if it also happens with the boost::python:list version.

**Comment by Theverat** [comment]
Have you tracked down where exactly the crash happens?
Try to create a debug build of pyluxcore and start Blender through gdb to get a backtrace:

To create debug build by editing these lines: https://github.com/LuxCoreRender/LuxCore/blob/25d466db3ab02784e4ba5a21948232b4db898f81/cmake/SpecializedConfig/Config_Linux-Static.cmake#L18

To start Blender through gdb, open a terminal, then:
`gdb /path/to/blender` 
`run`
Then bring Blender to crash, it will appear to freeze. Switch back to the gdb terminal, type:
`bt`
to get a backtrace.

**Comment by neo2068** [comment]
I did a backtrace and that is what I got.
`Thread 1 "blender" received signal SIGSEGV, Segmentation fault.
0x00007fffc5e6a83e in boost::python::converter::object_manager_traits<boost::python::numpy::ndarray>::get_pytype() ()
   from /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so
(gdb) bt
#0  0x00007fffc5e6a83e in boost::python::converter::object_manager_traits<boost::python::numpy::ndarray>::get_pytype() ()
    at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#1  0x00007fffc4c9b976 in luxcore::blender::Scene_DefineBlenderMeshExt1(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object const&, boost::python::api::object const&, unsigned int, boost::python::api::object const&) ()
    at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#2  0x00007fffc4c8e54c in boost::python::detail::caller_arity<11u>::impl<boost::python::list (*)(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object const&, boost::python::api::object const&, unsigned int, boost::python::api::object const&), boost::python::default_call_policies, boost::mpl::vector12<boost::python::list, luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, boost::python::api::object const&, boost::python::api::object const&, unsigned int, boost::python::api::object const&> >::operator()(_object*, _object*) ()
    at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#3  0x00007fffc5e5619d in boost::python::objects::function::call(_object*, _object*) const ()
    at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#4  0x00007fffc5e5634c in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
    at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#5  0x00007fffc5e5ca23 in boost::python::handle_exception_impl(boost::function0<void>) ()
    at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#6  0x00007fffc5e549a6 in function_call () at /home/michael/.config/blender/2.80/scripts/addons/BlendLuxCore/bin/pyluxcore.so

#7  0x000000000174fb44 in _PyObject_FastCallKeywords ()
#8  0x000000000114c90a in _PyEval_EvalFrameDefault ()
#9  0x0000000001145530 in  ()
#10 0x000000000114dfa3 in _PyEval_EvalFrameDefault ()
#11 0x0000000001145530 in  ()
#12 0x000000000114fa97 in _PyEval_EvalFrameDefault ()
#13 0x0000000001145530 in  ()
#14 0x000000000114fa97 in _PyEval_EvalFrameDefault ()
#15 0x0000000001145530 in  ()
#16 0x000000000114fa97 in _PyEval_EvalFrameDefault ()
#17 0x0000000001803c23 in _PyEval_EvalCodeWithName ()
#18 0x000000000174f4a6 in _PyFunction_FastCallKeywords ()
`

**Comment by neo2068** [comment]
With the new boost::python::list data types it works under Windows and Linux.

**Comment by neo2068** [comment]
@Dade916 @Theverat 
If there are no objections regarding the code, we I will merge the branch.

**Pull request merged**
