### PR TITLE
Fixes to glossy2 material

### PR DESCRIPTION
**Pull request by julescmay**
**Corrected discrepancy between cpu and ocl versions (also crash in cpu version) at low roughnesses**

I know people were complaining (and we also found) that sometimes a GPU render of a glossy surface came out significantly brighter than the same scene on CPU.  I tracked this down to very low roughnesses: at u/v roughness of 0.1, all was fine, but at 0.001 there were often significant differences.  I also found that different GPUs produced different errors: Intel (when it worked at all) was usually correct.  NVidia GeoForce had differences of up to 20%.  

I also found that at very-very low roughnesses (e.g. uroughness = 0.001, vroughness=0) the CPU would crash with an assertion failure caused by a number going denormalised.

The problem was: the code was underflowing on these very low numbers: the GPU brightness was caused by rounding errors and the crash was caused by division-by-nearly zero.  

The roughnesses were clamped to be above 1e-9,  I clamped them to 1e-5, and the problems went away.  (Clamped the same in both CPU and GPU, so they produce the same result).  I've also provided a tiny bit of hardening n the Schlick code.  At some point I want to revise these, so that they're well-behaved down to zero, but for now this avoids the errors and the crash.

**Glossy2 is now double-sided**

Not an error as such, but a real annoyance.  Both in CPU and GPU,  glossy2 had the coating only on the front side; the back side was always matte.  We had a lot of non-volume polygons in our scene, and we wanted them glossy both sides.  As was, we had to duplicate our polys. (Couldn't use two-sided, because the back-side of a two-sided is still the back-side, so can't be made coated using glossy2).

I've now changed that so that glossy2 is coated both sides - if you want it matte on the back, make it two-sided.  I think that, if the material is used either in a manifest poly, or with a volume, there won't be a performance hit because it will never evaluate the coating at the back side because no ray will ever reach it.

Hope these are useful.

### CODE REVIEW

**Comment by Dade916** [comment]
Thanks, can you add the support for a new ".doubleside" option to Glossy2 material properties ? You current code breaks the compatibility with the past while and it is something to avoid.
Adding a new ".doubleside" option (with default value "false") will maintain the compatibility with the past while offering access to the new feature if set true.

**Comment by julescmay** [comment]
OK, I can do that.

**Comment by Theverat** [comment]
Note that this fixes #301, which has a $100 bounty. You can claim that once the pull request is merged.

**Comment by julescmay** [comment]
Thanks, Theverat :-) I hadn't spotted that.

**Comment by julescmay** [comment]
Sorry it's taken me so long (ridiculous workload), but I've just pushed the .doublesided option you asked for.  Are you still interested?

**Comment by Dade916** [comment]
Yes, sure.

**Pull request merged**
